### ISSUE TITLE
Windup & Cooldown configurability

### ISSUE THREAD

**Issue by dylanjkl** [SuperRicky14/TpaPlusPlus#1]
I'd like to request the implementation of an optional togglable windup that makes it so when a player runs a command there is a timer until the command executes (e.g 10 seconds by default) and if the player is damaged/moved in that timeframe the command is cancelled.

I'd also like to request cooldown configurability so that the cooldown between command usage can be reduced/increased based on personal preference.

**Comment by SuperRicky14** [comment]
Sorry for the late reply, I have been busy for a while with alot of life stuff. I aim to port TPA++ to Fabric during the weekend, I will also include this feature in the next release.

So correct me if I am wrong, you want a feature  that if the player ran /TPA, they would have to wait 10 seconds (configurable) before actually sending the request.

Thank you for suggesting this feature!

**Comment by SuperRicky14** [comment]
~~Okay, I've made a working prototype of the Wind-up part in your request. But I will likely have to split this request into two different updates, since I need to rewrite a lot of the mod to get this to work correctly.~~

Windup's as well as some bug fixes, stability improvements and performance enhancements are out in the latest release (Check Modrinth if it's not yet out on CurseForge).

**Comment by SuperRicky14** [comment]
Cooldowns will be implemented on the next release, Scheduled for Sunday 14/4/2024.

**Comment by SuperRicky14** [comment]
Cooldowns have been finally implemented as of release 1.6
