### ISSUE TITLE
[Feature Request]: About Pull Request

### ISSUE THREAD

**Issue by half-nothing** [SuperRicky14/TpaPlusPlus#9]
### Description of feature request

I recently completed a port of 1.21.1 fabric and almost completely rewrote the module logic, although there are still some issues
[Branch link](https://github.com/half-nothing/TpaPlusPlus)
You can get the test build from this [link](https://github.com/half-nothing/TpaPlusPlus/actions)
I have developed it based on Architectury API, and I believe it won't be too difficult to port it to other platforms, although it will take some time
Now back to my question, I didn't just improve on one of your branches, I just created a new branch and now I don't know how to open a pull request merge my code

**Comment by SuperRicky14** [comment]
I believe in this case I have to re-base your branch on-top of the main one, once you are happy with it and it's on multiplatform I can merge it in for you! [You can quickly create a multiplatform project here](https://generate.architectury.dev/) if necessary.
By the way, is there a specific reasoning behind the change from MIT to LGPL in your code? This is mainly because the mods description states that the mod will always be open-source under the MIT license, and I would prefer to give a reasoning behind the change.
Aside from that the code looks pretty solid and much cleaner than the current branch!

**Comment by half-nothing** [comment]
My IDEA template is LGPL by default, I have not noticed this change, I will change back to MIT in the cross-platform version

**Comment by SuperRicky14** [comment]
Sorry this took so long, but it has finally been merged! I've made your fabric-1.21.1 branch the new default and the older branch is now called "multiplatform-legacy". Please let me know if I missed anything when bringing over the branch.
